
project_id = "lqepodeofiuvpffsmuol"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[storage]
enabled = true

[inbucket]
enabled = true

[functions.chess-api]
verify_jwt = true
