// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lqepodeofiuvpffsmuol.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxxZXBvZGVvZml1dnBmZnNtdW9sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMxNjk5NDksImV4cCI6MjA1ODc0NTk0OX0.0GIFlxx8d9Mf6bCMbj_BkPo3uxIhOYJq7GtdxnK9Pvk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);